default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: wdwe_development
  encoding: utf8
  host: localhost

test:
  <<: *default
  database: wdwe_test

production:
  <<: *default
  database: wdwe_production
